### PR TITLE
Log with zerolog, reduce deps

### PR DESCRIPTION
**Pull request by dim**

### CODE REVIEW

**Review by jpmedforth — APPROVED** [review]
So i can set bump to this version and set RUMOUR_LOG_LEVEL=warning?

**Comment by dim** [comment]
> So i can set bump to this version and set RUMOUR_LOG_LEVEL=warning?

Yes, that's the plan

**Comment by dim** [comment]
I think it's `warn` though

**Comment by dim** [comment]
Releasing as `blacksquaremedia/rumour:0.3.0`

**Pull request merged**
